#version 460
#extension GL_EXT_ray_tracing : require

layout(push_constant) uniform constants
{
	mat4 M;
} pushes;

layout(binding = 0) uniform UniformBufferObject {
    mat4 V, P, iV, iP;
} ubo;

layout(binding = 3) uniform accelerationStructureEXT topLevelAS;
layout(binding = 4, rgba32f) uniform image2D image;

void main()
{
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(0.5, 0.5, 0.5, 1.0));
}
